[package]
name = "rustnix"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9.0"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.9.8"
volatile = "0.2.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
