name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true

    - name: Install cargo bootimage
      run: cargo install bootimage

    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install -y qemu-system-x86

    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Build
      run: cargo build --verbose

    - name: Build bootimage
      run: cargo bootimage

    - name: Run tests
      run: cargo test --verbose

    - name: Run QEMU
      run: qemu-system-x86_64 -drive format=raw,file=target/x86_64-rustnix/debug/bootimage-rustnix.bin